### ISSUE TITLE
Ollama local LLM instead OpenAI issue

### ISSUE THREAD

**Issue by ciaotesla** [bhancockio/crewai-updated-tutorial-hierarchical#1]
I am testing this crewai example.
I modified using ollama as LLS and did the necessary changes.
I am getting this error:

`It seems we encountered an unexpected error while trying to use the tool. This was the error: Error code: 401 - {'error': {'message': 'Incorrect API key provided: DUMMY_KEY. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

Btw the code still runs but it repeats this error. So not sure what is happening. Will try to leave it running for a while.

I created a .env with a dummy OpenAI key, but this error persist.
Looks like CrewAI default to OpenAI and does not let me use my local LLM somehow.

I did other examples and look ok. Any idea?

**Comment by bhancockio** [comment]
Hey! I have a few questions for you to help me understand what's going wrong:
- Do you have Ollama installed and running on your computer?
- What is the name of the custom LLM you created?
- When you run `ollama list` what do you see?
- Could you please try `NA` instead of `DUMMY_KEY`
- Could you please send me a quick snippet of what your .env file looks like. Please make sure you don't share any secret keys when you post and can you pulease share  a snippet of the code where you create ChatOpenAI.

**Comment by ciaotesla** [comment]
Ok, I added the following lines to the .env

OPENAI_API_BASE='http://localhost:11434/v1'
OPENAI_MODEL_NAME='openhermes'
OPENAI_API_KEY=NA

and seems to work.
Hopefully they remove this OpenAI default from the api.
thx 
BTW great tutorials !

**Comment by ciaotesla** [comment]
I did more testing and getting this error, did you encounter this? I running crewai 16.3

`Traceback (most recent call last):
  File "/home/pi4/tweetbot/youtubeAI/main.py", line 71, in <module>
    results = crew.kickoff()
              ^^^^^^^^^^^^^^
  File "/home/pi4/tweetbot/.venv/lib/python3.11/site-packages/crewai/crew.py", line 213, in kickoff
    result, manager_metrics = self._run_hierarchical_process()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi4/tweetbot/.venv/lib/python3.11/site-packages/crewai/crew.py", line 273, in _run_hierarchical_process
    task_output = task.execute(
                  ^^^^^^^^^^^^^
  File "/home/pi4/tweetbot/.venv/lib/python3.11/site-packages/crewai/task.py", line 120, in execute
    task.thread.join()
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'join'
`
