### ISSUE TITLE
Hierarchical process error

### ISSUE THREAD

**Issue by SONYYA7** [bhancockio/crewai-updated-tutorial-hierarchical#7]
Traceback (most recent call last):
  File "/content/crewai-updated-tutorial-hierarchical/main.py", line 33, in <module>
    crew = Crew(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Crew
  Hierarchical process error: Tasks cannot be flagged with async_execution. [type=async_execution_in_hierarchical_process, input_value={'agents': [Agent(role=Ed...proxy=''), 'verbose': 2}, input_type=dict]

**Comment by mkiruba** [comment]
I am newbie in Python world, got this working like this

Forced to `pip install crewai`

Still got this error 
ModuleNotFoundError: No module named 'pkg_resources'

So installed `pip install setuptools`
